server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: product-service
      authentication-database: admin